### ISSUE TITLE
Failed to load entry point 'list': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user

### ISSUE THREAD

**Issue by cardboardcode** [cardboardcode/virtual_camera#6]
## Issue Description

Encountered the following error in terminal when running `ros2 topic list`:

```bash
/home/cardboardvoice/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/cardboardvoice/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/cardboardvoice/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Failed to load entry point 'list': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Traceback (most recent call last):
  File "/opt/ros/galactic/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.13.3', 'console_scripts', 'ros2')()
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2cli/cli.py", line 39, in main
    add_subparsers_on_demand(
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 250, in add_subparsers_on_demand
    extension.add_arguments(
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2topic/command/topic.py", line 29, in add_arguments
    add_subparsers_on_demand(
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 237, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'list'

```
This is in response to debugging another issue that mysteriously disallows proper publication of `sensor_msgs::msg::Image` within ROS2 Galactic and ROS2 Rolling.

**Comment by cardboardcode** [comment]
## Issue Reference 

https://docs.ros.org/en/rolling/How-To-Guides/Installation-Troubleshooting.html#import-failing-without-library-present-on-the-system

**Comment by cardboardcode** [comment]
## Attempted Solution

```bash
export PATH=/opt/ros/galactic/bin
```
Upon running `ros2 topic`, the following warning is outputted to terminal:
```bash
Failed to load entry point 'bw': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'delay': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'echo': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'find': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'hz': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'info': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'list': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'pub': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'type': /opt/ros/galactic/lib/librcl_logging_interface.so: undefined symbol: rcutils_expand_user
The C extension '/opt/ros/galactic/lib/python3.8/site-packages/rclpy/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
usage: ros2 topic [-h] [--include-hidden-topics] Call `ros2 topic <command> -h` for more detailed usage. ...

```

**Comment by cardboardcode** [comment]
## Solution (?) :raised_eyebrow: 

```bash
sudo apt-get install ros-galactic-rcutils --reinstall
```
